"use server";

import { Types } from "mongoose";
import databases from "@root/src/databases";
import { canAccessAdmin, requireSessionUser } from "./context";

type TicketMessage = { authorId: string; authorName: string; body: string; createdAt: Date; internal?: boolean };
type TicketRecord = { _id: unknown; createdAt: Date; updatedAt?: Date; messages?: TicketMessage[]; [key: string]: unknown };
const DEFAULT_SETTINGS = { discordInviteUrl: "", enabled: true, welcomeTitle: "Como podemos ajudar?", welcomeText: "Abra um ticket pelo site e nossa equipe responderá por aqui." };
function clean(value: unknown, max: number): string { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function serialize(ticket: unknown) { const raw = ticket as TicketRecord; return { ...raw, id: String(raw._id), _id: undefined, createdAt: new Date(raw.createdAt).toISOString(), updatedAt: raw.updatedAt ? new Date(raw.updatedAt).toISOString() : new Date(raw.createdAt).toISOString(), messages: (raw.messages || []).map((message) => ({ ...message, createdAt: new Date(message.createdAt).toISOString() })) }; }
export async function getSupportSettings() { const item = await databases.globalSettings.findOne({ key: "support" }).lean(); return { ...DEFAULT_SETTINGS, ...(item?.value || {}) }; }
export async function updateSupportSettings(input: { discordInviteUrl: string; enabled: boolean; welcomeTitle?: string; welcomeText?: string }) { const adminId = await requireSessionUser(); if (!(await canAccessAdmin(adminId))) throw new Error("Acesso administrativo necessário."); const url = clean(input.discordInviteUrl, 500); if (url && !/^https:\/\/discord\.gg\//i.test(url) && !/^https:\/\/discord\.com\/invite\//i.test(url)) throw new Error("Informe um link válido do servidor Discord."); const value = { ...DEFAULT_SETTINGS, discordInviteUrl: url, enabled: Boolean(input.enabled), welcomeTitle: clean(input.welcomeTitle, 100) || DEFAULT_SETTINGS.welcomeTitle, welcomeText: clean(input.welcomeText, 300) || DEFAULT_SETTINGS.welcomeText }; await databases.globalSettings.updateOne({ key: "support" }, { $set: { value } }, { upsert: true }); return value; }
export async function createWebSupportTicket(input: { subject: string; category: string; body: string }) { const userId = await requireSessionUser(); const settings = await getSupportSettings(); if (!settings.enabled) throw new Error("O suporte via site está temporariamente indisponível."); const subject = clean(input.subject, 160); const body = clean(input.body, 4000); if (!subject || !body) throw new Error("Informe o assunto e descreva como podemos ajudar."); const allowedCategories = ["technical", "application", "payment", "account", "store", "suggestion"]; const category = allowedCategories.includes(input.category) ? input.category : "account"; const user = await databases.siteUsers.findOne({ discordId: userId }).lean(); const now = new Date(); const ticket = await databases.supportTickets.create({ guildId: "web", channelId: new Types.ObjectId().toString(), userId, requesterEmail: user?.email, subject, category, priority: "normal", source: "web", status: "open", participants: [userId], messages: [{ authorId: userId, authorName: user?.name || "Usuário", body, createdAt: now }] }); return serialize(ticket.toObject()); }
export async function listMySupportTickets() { const userId = await requireSessionUser(); const tickets = await databases.supportTickets.find({ userId, source: "web" }).sort({ updatedAt: -1, createdAt: -1 }).lean(); return tickets.map(serialize); }
export async function getMySupportTicket(ticketId: string) { const userId = await requireSessionUser(); if (!Types.ObjectId.isValid(ticketId)) throw new Error("Ticket inválido."); const ticket = await databases.supportTickets.findOne({ _id: ticketId, userId, source: "web" }).lean(); if (!ticket) throw new Error("Ticket não encontrado."); return serialize(ticket); }
export async function addSupportTicketMessage(ticketId: string, body: string) { const userId = await requireSessionUser(); const text = clean(body, 4000); if (!text || !Types.ObjectId.isValid(ticketId)) throw new Error("Escreva uma mensagem válida."); const user = await databases.siteUsers.findOne({ discordId: userId }).lean(); const result = await databases.supportTickets.findOneAndUpdate({ _id: ticketId, userId, source: "web", status: { $ne: "closed" } }, { $push: { messages: { authorId: userId, authorName: user?.name || "Usuário", body: text, createdAt: new Date() } }, $set: { status: "waiting_staff", updatedAt: new Date() } }, { new: true }).lean(); if (!result) throw new Error("Este ticket não está disponível para novas mensagens."); return serialize(result); }
export async function listAllSupportTickets() { const adminId = await requireSessionUser(); if (!(await canAccessAdmin(adminId))) throw new Error("Acesso administrativo necessário."); const tickets = await databases.supportTickets.find({ source: "web" }).sort({ status: 1, priority: -1, updatedAt: -1 }).lean(); return tickets.map(serialize); }
export async function updateSupportTicket(input: { ticketId: string; status?: string; priority?: string; assignedTo?: string; subject?: string; addUserId?: string }) { const adminId = await requireSessionUser(); if (!(await canAccessAdmin(adminId))) throw new Error("Acesso administrativo necessário."); if (!Types.ObjectId.isValid(input.ticketId)) throw new Error("Ticket inválido."); const set: Record<string, unknown> = { updatedAt: new Date() }; if (input.status && ["open", "waiting_user", "waiting_staff", "closed"].includes(input.status)) set.status = input.status; if (input.priority && ["low", "normal", "high", "urgent"].includes(input.priority)) set.priority = input.priority; if (input.assignedTo !== undefined) set.assignedTo = clean(input.assignedTo, 80) || undefined; if (input.subject !== undefined) set.subject = clean(input.subject, 160); const update: { $set: Record<string, unknown>; $addToSet?: { participants: string } } = { $set: set }; if (input.addUserId && /^\d{15,25}$/.test(input.addUserId)) update.$addToSet = { participants: input.addUserId }; const ticket = await databases.supportTickets.findOneAndUpdate({ _id: input.ticketId, source: "web" }, update, { new: true }).lean(); if (!ticket) throw new Error("Ticket não encontrado."); return serialize(ticket); }
export async function addAdminTicketMessage(ticketId: string, body: string) { const adminId = await requireSessionUser(); if (!(await canAccessAdmin(adminId))) throw new Error("Acesso administrativo necessário."); const text = clean(body, 4000); if (!text || !Types.ObjectId.isValid(ticketId)) throw new Error("Escreva uma mensagem válida."); const admin = await databases.siteUsers.findOne({ discordId: adminId }).lean(); const ticket = await databases.supportTickets.findOneAndUpdate({ _id: ticketId, source: "web" }, { $push: { messages: { authorId: adminId, authorName: admin?.name || "Equipe ZUROS", body: text, createdAt: new Date() } }, $set: { status: "waiting_user", updatedAt: new Date() } }, { new: true }).lean(); if (!ticket) throw new Error("Ticket não encontrado."); return serialize(ticket); }
