import crypto from "node:crypto";
import { Types } from "mongoose";
import databases from "@root/src/databases";
import { changeApplicationMainServer, changeApplicationName, changeApplicationToken, listBotGuilds, restartApplication, startApplication, stopApplication } from "@root/src/integration/apps";
import { fail, readJson, requestId, text } from "@/lib/integration-api";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Context={params:Promise<{path:string[]}>};
const nonces=new Map<string,number>();
function respond(data:Record<string,unknown>,id:string,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Request-ID":id}})}
function safe(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
async function authenticate(request:Request,route:string,id:string){const secret=process.env.ZUROS_BRIDGE_CREDENTIAL?.trim();if(!secret)return fail("CONFIGURATION_REQUIRED","API do bot não configurada.",id,503);const bearer=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();const timestamp=request.headers.get("x-zuros-timestamp")||"",nonce=request.headers.get("x-zuros-nonce")||"",signature=request.headers.get("x-zuros-signature")||"";if(!safe(bearer,secret)||!/^\d{10}$/.test(timestamp)||!nonce||!signature)return fail("INVALID_CREDENTIAL","Assinatura inválida.",id,401);const now=Math.floor(Date.now()/1000),ts=Number(timestamp);if(Math.abs(now-ts)>300)return fail("INVALID_CREDENTIAL","Assinatura expirada.",id,401);for(const [key,expires] of nonces)if(expires<now)nonces.delete(key);if(nonces.has(nonce))return fail("INVALID_CREDENTIAL","Requisição repetida.",id,409);const raw=await request.clone().text();const url=new URL(request.url);const relative=`/${route}${url.search}`;const bodyHash=crypto.createHash("sha256").update(raw).digest("hex");const payload=[request.method.toUpperCase(),relative,timestamp,nonce,bodyHash].join("\n");const expected=crypto.createHmac("sha256",secret).update(payload).digest("hex");if(!safe(signature,expected))return fail("INVALID_CREDENTIAL","Assinatura inválida.",id,401);nonces.set(nonce,now+300);return null}
function appView(value:unknown){const app=value as Record<string,unknown>;return {id:String(app._id),application_id:String(app._id),name:app.name,botId:app.botId,bot_id:app.botId,serverId:app.serverId||null,status:app.status,version:app.version,lifetime:!!app.lifetime,expiresAt:app.expiresAt||null,online:false,forceUpdate:!!app.forceUpdate}}
async function owned(id:string,userId:string){if(!Types.ObjectId.isValid(id))return null;return databases.applications.findOne({_id:id,ownerId:userId}).select("-token").lean()}
function apiError(error:unknown,id:string){console.error(`[client-bot:${id}]`,error instanceof Error?error.name:"unknown");return fail("INTERNAL_ERROR",error instanceof Error?error.message:"Falha ao processar operação.",id,500)}
export async function GET(request:Request,context:Context){const id=requestId(request),route=(await context.params).path.join("/");const blocked=await authenticate(request,route,id);if(blocked)return blocked;try{const url=new URL(request.url),userId=url.searchParams.get("discord_user_id")?.trim()||"";if(route==="status")return respond({service:"zuros-client-bot",status:"operational",version:"v1"},id);if(route==="stats"){const filter=userId?{ownerId:userId}:{};const [applications,active]=await Promise.all([databases.applications.countDocuments(filter),databases.applications.countDocuments({...filter,status:"active"})]);return respond({applications,active},id)}if(route==="applications"){if(!userId)return fail("INVALID_REQUEST","discord_user_id obrigatório.",id,400);const apps=await databases.applications.find({ownerId:userId}).select("-token").sort({_id:-1}).lean();return respond({applications:apps.map(appView)},id)}const match=route.match(/^applications\/([^/]+)$/);if(match){if(!userId)return fail("INVALID_REQUEST","discord_user_id obrigatório.",id,400);const app=await owned(match[1],userId);return app?respond(appView(app),id):fail("NOT_FOUND","Aplicação não encontrada.",id,404)}const guilds=route.match(/^applications\/([^/]+)\/guilds$/);if(guilds){if(!userId)return fail("INVALID_REQUEST","discord_user_id obrigatório.",id,400);return respond({guilds:await listBotGuilds(guilds[1],userId)},id)}return fail("NOT_FOUND","Rota não encontrada.",id,404)}catch(error){return apiError(error,id)}}
export async function POST(request:Request,context:Context){const id=requestId(request),route=(await context.params).path.join("/");const blocked=await authenticate(request,route,id);if(blocked)return blocked;try{const body=await readJson(request),userId=text(body.discord_user_id,32);if(!userId)return fail("INVALID_REQUEST","discord_user_id obrigatório.",id,400);const match=route.match(/^applications\/([^/]+)\/(start|stop|restart|update|renew)$/);if(!match)return fail("NOT_FOUND","Rota não encontrada.",id,404);if(!(await owned(match[1],userId)))return fail("NOT_FOUND","Aplicação não encontrada.",id,404);if(match[2]==="start")await startApplication(match[1],userId);else if(match[2]==="stop")await stopApplication(match[1],userId);else if(match[2]==="restart")await restartApplication(match[1],userId);else if(match[2]==="update")await databases.applications.updateOne({_id:match[1],ownerId:userId},{$set:{forceUpdate:true,errorOnUpdate:false},$unset:{errorOnUpdateMessage:1}});else return fail("INVALID_REQUEST","A renovação deve ser paga pelo painel ZUROS.",id,409);return respond({success:true,action:match[2]},id)}catch(error){return apiError(error,id)}}
export async function PATCH(request:Request,context:Context){const id=requestId(request),route=(await context.params).path.join("/");const blocked=await authenticate(request,route,id);if(blocked)return blocked;try{const body=await readJson(request),userId=text(body.discord_user_id,32);if(!userId)return fail("INVALID_REQUEST","discord_user_id obrigatório.",id,400);const token=route.match(/^applications\/([^/]+)\/token$/);if(token){const value=text(body.token,256);if(!value)return fail("INVALID_REQUEST","token obrigatório.",id,400);await changeApplicationToken(token[1],userId,value);return respond({success:true},id)}const server=route.match(/^applications\/([^/]+)\/main-server$/);if(server){const guild=text(body.guild_id,32);if(!guild)return fail("INVALID_REQUEST","guild_id obrigatório.",id,400);await changeApplicationMainServer(server[1],userId,guild);return respond({success:true},id)}const app=route.match(/^applications\/([^/]+)$/);if(app){const name=text(body.name,40);if(!name)return fail("INVALID_REQUEST","name obrigatório.",id,400);await changeApplicationName(app[1],userId,name);return respond({success:true},id)}return fail("NOT_FOUND","Rota não encontrada.",id,404)}catch(error){return apiError(error,id)}}