import crypto from "node:crypto";
import databases from "@root/src/databases";
import { recordActivity } from "@root/src/integration/activity-log";
import { authRequest, fail, isAuthorized, ok, readJson, requestId, text } from "@/lib/integration-api";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Context={params:Promise<{path:string[]}>};
function denied(request:Request,id:string){return isAuthorized(request)?null:fail("INVALID_CREDENTIAL","Credencial da integração inválida.",id,401)}
function authError(error:unknown,id:string){const message=error instanceof Error?error.message:"";if(message==="AUTH_NOT_CONFIGURED")return fail("CONFIGURATION_REQUIRED","Configure ZUROS_AUTH_ID e ZUROS_BOT_CREDENTIAL na Vercel.",id,503);if(message==="AUTH_NOT_FOUND")return fail("NOT_FOUND","Integração Auth não encontrada.",id,404);console.error(`[integration:${id}]`,error instanceof Error?error.name:"unknown");return fail("UPSTREAM_ERROR","Não foi possível acessar o ZUROS Auth.",id,502)}
async function proxyAuth(authId:string,path:string,id:string,init?:RequestInit){try{const response=await authRequest(authId,path,init);if(response.status>=400)return fail("UPSTREAM_ERROR",`ZUROS Auth recusou a operação (HTTP ${response.status}).`,id,response.status===401||response.status===403?502:response.status);return ok(response.data,id)}catch(error){return authError(error,id)}}
export async function GET(request:Request,context:Context){const id=requestId(request),blocked=denied(request,id);if(blocked)return blocked;const route=(await context.params).path.join("/");try{
if(route==="health")return ok({service:"zuros-integration",status:"ok",version:"1",timestamp:new Date().toISOString()},id);
if(route==="status")return ok({service:"zuros-integration",status:"operational",configuration:{bridge:true,mongodb:Boolean(process.env.MONGO_URL||process.env.MONGODB_URI),auth:Boolean(process.env.ZUROS_AUTH_ID&&process.env.ZUROS_BOT_CREDENTIAL)}},id);
if(route==="config")return ok({api_version:"v1",heartbeat_seconds:60,events_reconnect_seconds:5,auth_base_url:"/api/integration/v1/auths",features:{products:true,heartbeat:true,auth:true,role_sync:true,events:true}},id);
if(route==="stats"){const [applications,products,activeAuths]=await Promise.all([databases.applications.countDocuments({status:"active"}),databases.products.countDocuments({}),databases.authLicenses.countDocuments({status:"active"})]);return ok({applications,products,active_auths:activeAuths,generated_at:new Date().toISOString()},id)}
if(route==="products"){const products=await databases.products.find({}).select("name productType prices runtimeEnvironment currentReleaseVersion lastReleaseCreatedVersion").lean();return ok({items:products.map(product=>({id:String(product._id),name:product.name,type:product.productType,prices:product.prices||{},runtime:product.runtimeEnvironment,version:product.currentReleaseVersion||product.lastReleaseCreatedVersion||"1.0.0"}))},id)}
const stats=route.match(/^auths\/([^/]+)\/stats$/);if(stats)return proxyAuth(stats[1],"/internal/integration/status",id);
const pending=route.match(/^auths\/([^/]+)\/role-sync\/pending$/);if(pending)return proxyAuth(pending[1],"/internal/role-sync/pending",id);
const events=route.match(/^auths\/([^/]+)\/events$/);if(events){try{await authRequest(events[1],"/internal/integration/status");return new Response(`id: ${crypto.randomUUID()}\nevent: connected\ndata: {"status":"connected"}\n\n`,{headers:{"Content-Type":"text/event-stream","Cache-Control":"no-store",Connection:"keep-alive","X-Request-ID":id}})}catch(error){return authError(error,id)}}
return fail("NOT_FOUND","Rota da integração não encontrada.",id,404)}catch(error){console.error(`[integration:${id}] GET`,error instanceof Error?error.name:"unknown");return fail("INTERNAL_ERROR","Falha interna ao processar a integração.",id,500)}}
export async function POST(request:Request,context:Context){const id=requestId(request),blocked=denied(request,id);if(blocked)return blocked;const route=(await context.params).path.join("/");try{const body=await readJson(request);
if(route==="heartbeat"){const botId=text(body.discord_bot_id,32),guildId=text(body.guild_id,32),version=text(body.version,32),uptime=typeof body.uptime==="number"&&Number.isFinite(body.uptime)&&body.uptime>=0?Math.floor(body.uptime):null;if(!botId||!guildId||!version||uptime===null)return fail("INVALID_REQUEST","Heartbeat inválido.",id,400);const application=await databases.applications.findOne({botId}).select("storeId status").lean();if(!application)return fail("NOT_FOUND","Aplicação não encontrada para este bot.",id,404);recordActivity({source:"bot",level:"success",storeId:String(application.storeId),message:`Heartbeat ${botId} v${version}`});return ok({accepted:true,application_status:application.status,received_at:new Date().toISOString()},id,202)}
const link=route.match(/^auths\/([^/]+)\/auth-link$/);if(link){const userId=text(body.user_id,32),guildId=text(body.guild_id,32);if(!userId||!guildId)return fail("INVALID_REQUEST","user_id e guild_id são obrigatórios.",id,400);return proxyAuth(link[1],"/internal/auth-link",id,{method:"POST",body:JSON.stringify({discord_user_id:userId,guild_id:guildId})})}
const ack=route.match(/^auths\/([^/]+)\/role-sync\/([^/]+)\/ack$/);if(ack){const status=text(body.status,32);if(!status||!["success","failed","retry"].includes(status))return fail("INVALID_REQUEST","status inválido.",id,400);return proxyAuth(ack[1],`/internal/role-sync/${encodeURIComponent(ack[2])}/ack?success=${status==="success"}`,id,{method:"POST",body:"{}"})}
return fail("NOT_FOUND","Rota da integração não encontrada.",id,404)}catch(error){if(error instanceof SyntaxError||(error instanceof Error&&["INVALID_JSON","PAYLOAD_TOO_LARGE"].includes(error.message)))return fail("INVALID_REQUEST","Corpo JSON inválido ou grande demais.",id,400);console.error(`[integration:${id}] POST`,error instanceof Error?error.name:"unknown");return fail("INTERNAL_ERROR","Falha interna ao processar a integração.",id,500)}}