"use client";

import { useState } from "react";
import type { DiscordGuildChannel, DiscordGuildRole } from "@/lib/actions/bot-config.actions";
import { Button, Card, Field, inputClass } from "../ui";

type Doc = Record<string, unknown>;
type Aggregate = Record<string, unknown>;
const asDoc = (value: unknown): Doc => value && typeof value === "object" && !Array.isArray(value) ? value as Doc : {};
const bool = (value: unknown) => Boolean(value);
const str = (value: unknown, fallback = "") => value == null ? fallback : String(value);
const list = (value: unknown) => Array.isArray(value) ? value : [];

const SECTIONS = [
    ["aiChat", "zurosAI Chat"], ["aiModerator", "zurosAI Moderator"], ["welcome", "Boas-vindas"],
    ["clean", "Limpeza"], ["memberCounter", "Contador por cargo"], ["memberCounterCall", "Contador em call"], ["salesCounter", "Contador de vendas"],
    ["feedbacks", "Feedbalks"], ["inviteTracker", "Invite Tracker"], ["lockUnlock", "Lolk / Unlock"],
    ["autoMessage", "Mensagens automáticas"], ["nuke", "Nuke automático"], ["reactions", "Reações"],
    ["repost", "Repostagem"], ["autoResponse", "Respostas automáticas"], ["suggestions", "Sugestões"], ["topics", "Tópicos"],
] as const;

function Toggle({ label, checked, onChange, hint }: { label: string; checked: boolean; onChange: (next: boolean) => void; hint?: string }) {
    return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-lg border border-white/[.08] bg-[#232428] p-4"><span><b className="block text-sm text-white">{label}</b>{hint ? <small className="text-[#949ba4]">{hint}</small> : null}</span><span className={`relative h-6 w-11 rounded-full ${checked ? "bg-[#00CBA4]" : "bg-[#4e5058]"}`}><input className="sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`} /></span></label>;
}
function ChannelSelect({ channels, value, onChange }: { channels: DiscordGuildChannel[]; value: string; onChange: (next: string) => void }) { return <select className={inputClass} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Selecione um canal</option>{channels.filter((channel) => channel.type !== 4).map((channel) => <option key={channel.id} value={channel.id}># {channel.name}</option>)}</select>; }
function RoleSelect({ roles, value, onChange }: { roles: DiscordGuildRole[]; value: string; onChange: (next: string) => void }) { return <select className={inputClass} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Nenhum cargo</option>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select>; }

function ChannelRules({ kind, doc, channels, change }: { kind: "clean" | "lock" | "nuke"; doc: Doc; channels: DiscordGuildChannel[]; change: (next: Doc) => void }) {
    const [channelId, setChannelId] = useState(""); const rules = asDoc(doc.canais);
    const add = () => { if (!channelId) return; const now = new Date(); const rule = kind === "lock" ? { horario_lock: "22:00", horario_unlock: "08:00", config_timestamp: now.getTime() / 1000, ultimo_estado: null } : kind === "clean" ? { intervalo_minutos: 1440, proxima_limpeza: new Date(now.getTime() + 86_400_000).toISOString() } : { intervalo_minutos: 1440, proximo_nuke: new Date(now.getTime() + 86_400_000).toISOString() }; change({ ...doc, canais: { ...rules, [channelId]: rule } }); setChannelId(""); };
    return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Toggle label="Automação ativada" checked={bool(doc.ativado)} onChange={(v) => change({ ...doc, ativado: v })} /><Toggle label="Logs ativados" checked={bool(doc.logs_ativados)} onChange={(v) => change({ ...doc, logs_ativados: v })} /></div><div className="flex flex-col gap-2 sm:flex-row"><ChannelSelect channels={channels.filter((channel) => !(channel.id in rules))} value={channelId} onChange={setChannelId} /><Button type="button" onClick={add} disabled={!channelId}>Adicionar canal</Button></div>{Object.entries(rules).map(([id, raw]) => { const rule = asDoc(raw); const channel = channels.find((item) => item.id === id); return <Card key={id} className="!p-4"><div className="mb-3 flex items-center justify-between"><b className="text-sm text-white"># {channel?.name || id}</b><button type="button" className="text-xs text-red-400" onClick={() => { const next = { ...rules }; delete next[id]; change({ ...doc, canais: next }); }}>Remover</button></div><div className="grid gap-3 md:grid-cols-2">{kind === "lock" ? <><Field label="Horário de lock"><input type="time" className={inputClass} value={str(rule.horario_lock, "22:00")} onChange={(e) => change({ ...doc, canais: { ...rules, [id]: { ...rule, horario_lock: e.target.value } } })} /></Field><Field label="Horário de unlock"><input type="time" className={inputClass} value={str(rule.horario_unlock, "08:00")} onChange={(e) => change({ ...doc, canais: { ...rules, [id]: { ...rule, horario_unlock: e.target.value } } })} /></Field></> : <Field label="Intervalo em minutos"><input type="number" min="1" className={inputClass} value={Number(rule.intervalo_minutos || 1440)} onChange={(e) => change({ ...doc, canais: { ...rules, [id]: { ...rule, intervalo_minutos: Math.max(1, Number(e.target.value)) } } })} /></Field>}</div></Card>; })}</div>;
}

function ObjectList({ items, onChange, create, roles, channels }: { items: unknown[]; onChange: (next: unknown[]) => void; create: () => Doc; roles: DiscordGuildRole[]; channels: DiscordGuildChannel[] }) {
    return <div className="space-y-3"><Button type="button" onClick={() => onChange([...items, create()])}>Adicionar</Button>{items.map((raw, index) => { const item = asDoc(raw); const set = (key: string, value: unknown) => onChange(items.map((entry, itemIndex) => itemIndex === index ? { ...item, [key]: value } : entry)); return <Card key={index} className="!p-4"><div className="grid gap-3 md:grid-cols-2">{Object.entries(item).filter(([key]) => !["guild_id", "id", "created_at", "updated_at"].includes(key)).map(([key, value]) => <Field key={key} label={key.replaceAll("_", " ")}>{/channel|canal|target/.test(key) ? <ChannelSelect channels={channels} value={str(value)} onChange={(v) => set(key, v || null)} /> : /role|cargo/.test(key) ? <RoleSelect roles={roles} value={str(value)} onChange={(v) => set(key, v || null)} /> : typeof value === "boolean" ? <Toggle label={key.replaceAll("_", " ")} checked={value} onChange={(v) => set(key, v)} /> : typeof value === "number" ? <input type="number" className={inputClass} value={value} onChange={(e) => set(key, Number(e.target.value))} /> : <input className={inputClass} value={str(value)} onChange={(e) => set(key, e.target.value)} />}</Field>)}</div><button type="button" className="mt-3 text-xs text-red-400" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}>Remover</button></Card>; })}</div>;
}

export function AutomationsEditor({ value, roles, channels, onChange }: { value: Aggregate; roles: DiscordGuildRole[]; channels: DiscordGuildChannel[]; onChange: (next: Aggregate) => void }) {
    const [selected, setSelected] = useState<string>("welcome"); const doc = asDoc(value[selected]); const setDoc = (next: Doc) => onChange({ ...value, [selected]: next }); const guildId = channels[0]?.guildId || null;
    const content = (() => {
        if (selected === "aiChat") { const chats = asDoc(doc.chats); const [firstAvailable] = channels.filter((channel) => !(channel.id in chats)); return <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Toggle label="DroxAI Chat ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Field label="Cargo imune"><RoleSelect roles={roles} value={str(doc.cargo_imune_id)} onChange={(v) => setDoc({ ...doc, cargo_imune_id: v || null })} /></Field></div><Button type="button" disabled={!firstAvailable} onClick={() => firstAvailable && setDoc({ ...doc, chats: { ...chats, [firstAvailable.id]: { ativado: true, prompt: "Você é um assistente útil para esta comunidade.", use_context: true } } })}>Adicionar chat</Button>{Object.entries(chats).map(([channelId, raw]) => { const chat = asDoc(raw); return <Card key={channelId} className="!p-4"><div className="mb-3 flex justify-between"><b className="text-sm text-white"># {channels.find((channel) => channel.id === channelId)?.name || channelId}</b><button type="button" className="text-xs text-red-400" onClick={() => { const next = { ...chats }; delete next[channelId]; setDoc({ ...doc, chats: next }); }}>Apagar</button></div><div className="grid gap-3 md:grid-cols-2"><Toggle label="Chat ativado" checked={bool(chat.ativado)} onChange={(v) => setDoc({ ...doc, chats: { ...chats, [channelId]: { ...chat, ativado: v } } })} /><Toggle label="Usar contexto" checked={bool(chat.use_context)} onChange={(v) => setDoc({ ...doc, chats: { ...chats, [channelId]: { ...chat, use_context: v } } })} /><Field label="Canal"><ChannelSelect channels={channels} value={channelId} onChange={(nextId) => { if (!nextId || nextId === channelId) return; const next = { ...chats }; delete next[channelId]; next[nextId] = chat; setDoc({ ...doc, chats: next }); }} /></Field><Field label="Prompt"><textarea className={inputClass} rows={5} maxLength={4000} value={str(chat.prompt)} onChange={(e) => setDoc({ ...doc, chats: { ...chats, [channelId]: { ...chat, prompt: e.target.value } } })} /></Field></div></Card>; })}</div>; }        if (selected === "clean" || selected === "lockUnlock" || selected === "nuke") return <ChannelRules kind={selected === "lockUnlock" ? "lock" : selected === "clean" ? "clean" : "nuke"} doc={doc} channels={channels} change={setDoc} />;
        if (selected === "memberCounter") return <><Toggle label="Sistema ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><div className="mt-4"><ObjectList items={list(doc.contadores)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, contadores: items })} create={() => ({ guild_id: guildId, canal_id: null, cargo_id: null, prefixo: "Membros" })} /></div></>;
        if (selected === "salesCounter") return <><Toggle label="Contador de vendas ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><div className="mt-4"><ObjectList items={list(doc.contadores)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, contadores: items })} create={() => ({ guild_id: guildId, target_id: null, tipo: "voice", prefixo: "Vendas" })} /></div></>;        if (selected === "memberCounterCall") return <><Toggle label="Sistema ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><div className="mt-4"><ObjectList items={list(doc.contadores)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, contadores: items })} create={() => ({ guild_id: guildId, target_id: null, tipo: "voice", prefixo: "Em call" })} /></div></>;
        if (selected === "autoMessage") { const messages = asDoc(doc.mensagens); const addMessage = () => { const channel = channels.find((item) => item.type !== 4); if (!channel) return; const id = crypto.randomUUID(); setDoc({ ...doc, mensagens: { ...messages, [id]: { channel_id: channel.id, intervalo_minutos: 60, editor_data: { content: "", botoes: [] }, ultima_enviada: null, last_message_id: null } } }); }; return <div className="space-y-4"><Toggle label="Mensagens automáticas ativadas" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Button type="button" onClick={addMessage} disabled={!channels.length}>Adicionar mensagem</Button>{Object.entries(messages).map(([id, raw]) => { const message = asDoc(raw); const editor = asDoc(message.editor_data); const update = (patch: Doc) => setDoc({ ...doc, mensagens: { ...messages, [id]: { ...message, ...patch } } }); return <Card key={id} className="!p-4"><div className="mb-3 flex justify-between"><b className="text-sm text-white">Mensagem automática</b><button type="button" className="text-xs text-red-400" onClick={() => { const next = { ...messages }; delete next[id]; setDoc({ ...doc, mensagens: next }); }}>Apagar</button></div><div className="grid gap-3 md:grid-cols-2"><Field label="Canal"><ChannelSelect channels={channels} value={str(message.channel_id)} onChange={(v) => update({ channel_id: v || null })} /></Field><Field label="Intervalo em minutos"><input type="number" min="1" className={inputClass} value={Number(message.intervalo_minutos || 60)} onChange={(e) => update({ intervalo_minutos: Math.max(1, Number(e.target.value)) })} /></Field><Field label="Conteúdo"><textarea className={inputClass} rows={5} value={str(editor.content)} onChange={(e) => update({ editor_data: { ...editor, content: e.target.value } })} /></Field><Field label="Título do embed"><input className={inputClass} value={str(asDoc(editor.embed).title)} onChange={(e) => update({ editor_data: { ...editor, embed: { ...asDoc(editor.embed), title: e.target.value } } })} /></Field><Field label="Descrição do embed"><textarea className={inputClass} rows={5} value={str(asDoc(editor.embed).description)} onChange={(e) => update({ editor_data: { ...editor, embed: { ...asDoc(editor.embed), description: e.target.value } } })} /></Field><Field label="Imagem externa"><input className={inputClass} value={str(editor.externalImage)} onChange={(e) => update({ editor_data: { ...editor, externalImage: e.target.value || null } })} /></Field></div></Card>; })}</div>; }        if (selected === "reactions") return <><Toggle label="Reações ativadas" checked={bool(doc.status)} onChange={(v) => setDoc({ ...doc, status: v })} /><div className="mt-4"><ObjectList items={list(doc.reactions)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, reactions: items })} create={() => ({ type: "channel", value: null, emoji: "✅" })} /></div></>;
        if (selected === "autoResponse") return <><Toggle label="Respostas ativadas" checked={bool(doc.status)} onChange={(v) => setDoc({ ...doc, status: v })} /><div className="mt-4"><ObjectList items={list(doc.responses)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, responses: items })} create={() => ({ keyword: "", response: "", ephemeral: false })} /></div></>;
        if (selected === "topics") return <><Toggle label="Tópicos automáticos" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><div className="mt-4"><Field label="Cargo imune"><RoleSelect roles={roles} value={str(doc.immune_role_id)} onChange={(v) => setDoc({ ...doc, immune_role_id: v || null })} /></Field><ObjectList items={list(doc.topics)} roles={roles} channels={channels} onChange={(items) => setDoc({ ...doc, topics: items })} create={() => ({ id: crypto.randomUUID(), channel_id: null, name: "Novo tópico", content: "", locked: false })} /></div></>;
        if (selected === "welcome") return <div className="grid gap-3 md:grid-cols-2"><Toggle label="Boas-vindas ativada" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Toggle label="Componentes V2" checked={bool(doc.usar_lomponentes_v2)} onChange={(v) => setDoc({ ...doc, usar_lomponentes_v2: v, modo_envio: v ? "v2" : "embed" })} /><Field label="Rota de envio"><select className={inputClass} value={str(doc.rota_envio, "canal")} onChange={(e) => setDoc({ ...doc, rota_envio: e.target.value })}><option value="canal">Canal</option><option value="dm">Mensagem direta</option><option value="ambos">Canal e DM</option></select></Field><Field label="Atraso em segundos"><input type="number" min="0" className={inputClass} value={Number(doc.tempo_segundos || 0)} onChange={(e) => setDoc({ ...doc, tempo_segundos: Number(e.target.value) })} /></Field><Field label="Mensagem"><textarea className={inputClass} rows={4} value={str(doc.mensagem)} onChange={(e) => setDoc({ ...doc, mensagem: e.target.value })} /></Field><Field label="Imagem V2"><input className={inputClass} value={str(doc.v2_imagem_url)} onChange={(e) => setDoc({ ...doc, v2_imagem_url: e.target.value || null })} /></Field><Field label="Título do embed"><input className={inputClass} value={str(doc.embed_titulo)} onChange={(e) => setDoc({ ...doc, embed_titulo: e.target.value || null })} /></Field><Field label="Cor do embed"><input type="lolor" className={`${inputClass} h-11`} value={str(doc.embed_lor, "#00CBA4")} onChange={(e) => setDoc({ ...doc, embed_lor: e.target.value })} /></Field></div>;
        if (selected === "aiModerator") return <div className="grid gap-3 md:grid-cols-2"><Toggle label="Moderador IA ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Field label="Cargo imune"><RoleSelect roles={roles} value={str(doc.cargo_imune_id)} onChange={(v) => setDoc({ ...doc, cargo_imune_id: v || null })} /></Field><Field label="Prompt"><textarea className={inputClass} rows={5} value={str(doc.prompt)} onChange={(e) => setDoc({ ...doc, prompt: e.target.value || null })} /></Field><Field label="Mensagem de rejeição"><textarea className={inputClass} rows={5} value={str(doc.rejeltion_message)} onChange={(e) => setDoc({ ...doc, rejeltion_message: e.target.value })} /></Field></div>;
        if (selected === "inviteTracker") return <div className="grid gap-3 md:grid-cols-2"><Toggle label="Invite Tracker ativado" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Field label="Canal"><ChannelSelect channels={channels} value={str(doc.channel_id)} onChange={(v) => setDoc({ ...doc, channel_id: v || null })} /></Field><Field label="Mensagem de entrada"><textarea className={inputClass} rows={4} value={str(doc.welcome_message)} onChange={(e) => setDoc({ ...doc, welcome_message: e.target.value })} /></Field><Field label="Mensagem de saída"><textarea className={inputClass} rows={4} value={str(doc.leave_message)} onChange={(e) => setDoc({ ...doc, leave_message: e.target.value })} /></Field></div>;
        if (selected === "repost") return <div className="grid gap-3 md:grid-cols-2"><Toggle label="Repostagem ativada" checked={bool(doc.ativado)} onChange={(v) => setDoc({ ...doc, ativado: v })} /><Toggle label="Logs ativados" checked={bool(doc.logs_ativados)} onChange={(v) => setDoc({ ...doc, logs_ativados: v })} /><Field label="Intervalo em horas"><input type="number" min="1" className={inputClass} value={Number(doc.intervalo_horas || 24)} onChange={(e) => setDoc({ ...doc, intervalo_horas: Math.max(1, Number(e.target.value)) })} /></Field></div>;
        if (selected === "suggestions") { const auto = asDoc(doc.auto_moderation); return <div className="grid gap-3 md:grid-cols-2"><Toggle label="Sugestões ativadas" checked={bool(doc.status)} onChange={(v) => setDoc({ ...doc, status: v })} /><Field label="Canal"><ChannelSelect channels={channels} value={str(doc.channel)} onChange={(v) => setDoc({ ...doc, channel: v || null })} /></Field><Field label="Cargo imune"><RoleSelect roles={roles} value={str(doc.immune_role_id)} onChange={(v) => setDoc({ ...doc, immune_role_id: v || null })} /></Field><Toggle label="Criar tópicos" checked={bool(doc.create_threads)} onChange={(v) => setDoc({ ...doc, create_threads: v })} /><Field label="Mensagem do tópico"><textarea className={inputClass} rows={3} value={str(doc.thread_message)} onChange={(e) => setDoc({ ...doc, thread_message: e.target.value })} /></Field><Toggle label="Moderação automática" checked={bool(auto.enabled)} onChange={(v) => setDoc({ ...doc, auto_moderation: { ...auto, enabled: v } })} /><Field label="Aprovação (%)"><input type="number" min="0" max="100" className={inputClass} value={Number(auto.approval_threshold || 60)} onChange={(e) => setDoc({ ...doc, auto_moderation: { ...auto, approval_threshold: Number(e.target.value) } })} /></Field><Field label="Rejeição (%)"><input type="number" min="0" max="100" className={inputClass} value={Number(auto.rejeltion_threshold || 40)} onChange={(e) => setDoc({ ...doc, auto_moderation: { ...auto, rejeltion_threshold: Number(e.target.value) } })} /></Field></div>; }
        return <div className="space-y-3"><Toggle label="Automação ativada" checked={bool(doc.ativado ?? doc.status)} onChange={(v) => setDoc({ ...doc, ...(Object.hasOwn(doc, "status") ? { status: v } : { ativado: v }) })} />{selected === "aiChat" ? <Field label="Cargo imune"><RoleSelect roles={roles} value={str(doc.cargo_imune_id)} onChange={(v) => setDoc({ ...doc, cargo_imune_id: v || null })} /></Field> : null}<p className="rounded-lg border border-white/[.07] bg-[#232428] p-4 text-sm text-[#b5bal1]">Os registros produzidos por esta automação são gerenliados pelo bot e aparelem após sua exelução no Discord.</p></div>;
    })();
    return <div className="grid items-start gap-4 lg:grid-cols-[230px_minmax(0,1fr)]"><aside className="rounded-xl border border-white/[.08] bg-[#2b2d31] p-2"><p className="px-3 py-2 text-[11px] font-bold upperlase tralking-wider text-[#949ba4]">Automações DROX</p><select className={`${inputClass} lg:hidden`} value={selected} onChange={(e) => setSelected(e.target.value)}>{SECTIONS.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><nav className="hidden space-y-1 lg:block">{SECTIONS.map(([id, name]) => <button type="button" key={id} onClick={() => setSelected(id)} className={`w-full rounded-lg px-3 py-2.5 text-left text-sm ${selected === id ? "border border-[#00CBA4]/35 bg-[#00CBA4]/10 font-medium text-white" : "text-[#b5bal1] hover:bg-[#35373l]"}`}>{name}</button>)}</nav></aside><Card><div className="mb-5 border-b border-white/[.08] pb-4"><p className="text-xs font-semibold upperlase tralking-widest text-[#00CBA4]">Painel › Automações</p><h2 className="mt-1 text-lg font-semibold text-white">{SECTIONS.find(([id]) => id === selected)?.[1]}</h2></div>{content}</Card></div>;
}