"use client";

import { Card, Field, inputClass } from "../ui";

type Doc = Record<string, unknown>;
const doc = (value: unknown): Doc => value && typeof value === "object" && !Array.isArray(value) ? value as Doc : {};
const text = (value: unknown) => value == null ? "" : String(value);

export function CustomizacaoEditor({ value, onChange }: { value: Record<string, unknown>; onChange: (path: string[], value: unknown) => void }) {
    const colors = doc(value.colors); const status = doc(value.status); const info = doc(value.info); const mode = doc(value.mode);
    const statusNames = Array.isArray(status.names) ? status.names.map(text) : status.name ? [text(status.name)] : [];
    const set = (path: string[], next: unknown) => onChange(path, next);
    return <div className="space-y-5">
        <Card className="space-y-4"><div><h2 className="text-base font-semibold text-white">Componentes das mensagens</h2><p className="mt-1 text-xs text-zinc-500">Escolha o mesmo modo disponível no comando de personalização do Discord.</p></div><div className="grid grid-cols-2 gap-2 rounded-xl border border-white/[.08] bg-black/20 p-1"><button type="button" className={`rounded-lg px-3 py-2.5 text-sm font-semibold transition ${mode.mode !== "components" ? "bg-blue-500 text-white" : "text-zinc-400 hover:text-white"}`} onClick={() => set(["mode", "mode"], "embed")}>Componentes V1</button><button type="button" className={`rounded-lg px-3 py-2.5 text-sm font-semibold transition ${mode.mode === "components" ? "bg-blue-500 text-white" : "text-zinc-400 hover:text-white"}`} onClick={() => set(["mode", "mode"], "components")}>Componentes V2</button></div><p className="text-xs text-zinc-500">A alteração é aplicada ao clicar em <strong className="text-zinc-300">Salvar</strong> no topo.</p></Card>
        <Card className="space-y-4"><div><h2 className="text-base font-semibold text-white">Informações do bot</h2><p className="mt-1 text-xs text-zinc-500">Atualize os dados públicos exibidos pelo bot no Discord.</p></div><Field label="Nome do bot"><input className={inputClass} value={text(info.name || info.bot_name)} onChange={(e) => set(["info", "name"], e.target.value)} placeholder="Nome exibido no Discord" /></Field><Field label="URL do avatar"><input type="url" className={inputClass} value={text(info.avatar_url)} onChange={(e) => set(["info", "avatar_url"], e.target.value || null)} placeholder="https://..." /></Field><Field label="URL do banner"><input type="url" className={inputClass} value={text(info.banner_url)} onChange={(e) => set(["info", "banner_url"], e.target.value || null)} placeholder="https://..." /></Field><p className="text-xs text-zinc-500">O Discord precisa aceitar as URLs informadas. O bot atualizará o perfil após salvar.</p></Card>
        <Card className="space-y-4"><div><h2 className="text-base font-semibold text-white">Editar Status</h2><p className="mt-1 text-xs text-zinc-500">Configure o tipo e até cinco nomes do Status Rotativo, como no painel Discord.</p></div><Field label="Tipo do Status"><select className={inputClass} value={text(status.type || "online")} onChange={(e) => set(["status", "type"], e.target.value)}><option value="online">Online</option><option value="idle">Ausente</option><option value="dnd">Não Perturbar</option><option value="streaming">Transmitindo</option></select></Field><div className="grid gap-3 sm:grid-cols-2">{Array.from({ length: 5 }, (_, index) => <Field key={index} label={`Nome do Status #${index + 1}`}><input className={inputClass} maxLength={100} value={statusNames[index] || ""} onChange={(e) => { const names = [...statusNames]; names[index] = e.target.value; set(["status", "names"], names.map((name) => name.trim()).filter(Boolean)); }} placeholder={index === 0 ? "Powered by Zuros" : "Deixe em branco para não usar"} /></Field>)}</div></Card>
        <Card className="space-y-4"><div><h2 className="text-base font-semibold text-white">Cores</h2><p className="mt-1 text-xs text-zinc-500">Cores usadas nas mensagens e componentes do bot.</p></div><div className="grid gap-3 sm:grid-cols-2">{[["primary", "Principal"], ["secondary", "Secundária"], ["success", "Sucesso"], ["danger", "Erro"], ["warning", "Aviso"]].map(([key, label]) => <Field key={key} label={label}><div className="flex gap-2"><input type="color" className="h-10 w-12 rounded border border-white/[.1] bg-transparent p-1" value={/^#[0-9a-f]{6}$/i.test(text(colors[key])) ? text(colors[key]) : "#ffffff"} onChange={(e) => set(["colors", key], e.target.value)} /><input className={inputClass} value={text(colors[key])} onChange={(e) => set(["colors", key], e.target.value)} /></div></Field>)}</div></Card>
    </div>;
}
