import nodemailer from "nodemailer";
import databases from "../databases";

type LoginContext = { ip: string; city: string; region: string; country: string };
export type CartNotification = { userId: string; cartId: string; type: "purchase" | "renewal"; productName: string; plan: string; amount: number; expiresAt?: Date | string | null; applicationName?: string };
function required(name: string): string { const value = process.env[name]?.trim(); if (!value) throw new Error(`A variável ${name} não está configurada.`); return value; }
function money(value: number): string { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value); }
function date(value?: Date | string | null): string { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)) : "—"; }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] || char); }
function transport() { const port = Number(process.env.EMAIL_SERVER_PORT || 587); return { host: required("EMAIL_SERVER_HOST"), port, secure: process.env.EMAIL_SERVER_SECURE === "true", auth: { user: required("EMAIL_SERVER_USER"), pass: required("EMAIL_SERVER_PASSWORD") }, connectionTimeout: 10_000, greetingTimeout: 10_000, socketTimeout: 15_000, requireTLS: process.env.EMAIL_SERVER_SECURE !== "true" }; }
export async function sendTransactionalEmail(input: { to: string; subject: string; text: string; html: string }) { if (!input.to) return; const transporter = nodemailer.createTransport(transport()); await transporter.sendMail({ from: required("EMAIL_FROM"), replyTo: required("EMAIL_FROM"), to: input.to, subject: input.subject, text: input.text, html: input.html, headers: { "Auto-Submitted": "auto-generated", "X-Auto-Response-Suppress": "All" } }); }
async function userEmail(userId: string): Promise<{ email: string; name: string } | null> { const user = await databases.siteUsers.findOne({ discordId: userId }, { email: 1, name: 1 }).lean(); return user?.email ? { email: user.email, name: user.name || "cliente" } : null; }
export async function sendLoginAlert(input: { userId: string; method: "Discord" | "e-mail"; context: LoginContext }) { const user = await userEmail(input.userId); if (!user) return; const place = [input.context.city, input.context.region, input.context.country].filter(Boolean).join(", ") || "localização não informada"; const subject = "Novo acesso à sua conta ZUROS"; const text = `Olá, ${user.name}.\n\nDetectamos um novo acesso à sua conta ZUROS.\nMétodo: ${input.method}\nData: ${date(new Date())}\nIP: ${input.context.ip}\nLocal aproximado: ${place}\n\nSe não foi você, entre em contato com o suporte.`; const html = `<div style="font-family:Arial,sans-serif;max-width:560px;color:#1f2933"><h2>Novo acesso à sua conta ZUROS</h2><p>Olá, ${escapeHtml(user.name)}. Detectamos um novo acesso:</p><ul><li><b>Método:</b> ${input.method}</li><li><b>Data:</b> ${date(new Date())}</li><li><b>IP:</b> ${escapeHtml(input.context.ip)}</li><li><b>Local aproximado:</b> ${escapeHtml(place)}</li></ul><p>Se não foi você, entre em contato com o suporte imediatamente.</p></div>`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export async function sendCartOpenedAlert(input: CartNotification) { const user = await userEmail(input.userId); if (!user) return; const kind = input.type === "renewal" ? "renovação" : "pedido"; const subject = `Seu ${kind} foi aberto na ZUROS`; const text = `Olá, ${user.name}.\n\nSeu ${kind} foi aberto.\nProduto: ${input.productName}\nPlano: ${input.plan}\nValor: ${money(input.amount)}\nValidade do carrinho: ${date(input.expiresAt)}\n\nAcesse o painel para concluir o pagamento.`; const html = `<div style="font-family:Arial,sans-serif;max-width:560px;color:#1f2933"><h2>${kind === "renovação" ? "Renovação" : "Pedido"} aberto</h2><p>Olá, ${escapeHtml(user.name)}. Seu ${kind} foi aberto.</p><p><b>Produto:</b> ${escapeHtml(input.productName)}<br><b>Plano:</b> ${escapeHtml(input.plan)}<br><b>Valor:</b> ${money(input.amount)}<br><b>Expira em:</b> ${date(input.expiresAt)}</p><p>Acesse o painel para concluir o pagamento.</p></div>`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export async function sendPaymentConfirmedAlert(input: CartNotification) { const user = await userEmail(input.userId); if (!user) return; const kind = input.type === "renewal" ? "renovação" : "pedido"; const subject = `Pagamento aprovado: ${input.productName}`; const text = `Olá, ${user.name}.\n\nSeu pagamento foi aprovado.\nTipo: ${kind}\nProduto: ${input.productName}\nPlano: ${input.plan}\nValor: ${money(input.amount)}\n${input.applicationName ? `Aplicação: ${input.applicationName}\n` : ""}${input.expiresAt ? `Válido até: ${date(input.expiresAt)}\n` : ""}\nAcesse o painel para acompanhar sua aplicação.`; const html = `<div style="font-family:Arial,sans-serif;max-width:560px;color:#1f2933"><h2>Pagamento aprovado</h2><p>Olá, ${escapeHtml(user.name)}. Seu ${kind} foi confirmado.</p><p><b>Produto:</b> ${escapeHtml(input.productName)}<br><b>Plano:</b> ${escapeHtml(input.plan)}<br><b>Valor:</b> ${money(input.amount)}${input.applicationName ? `<br><b>Aplicação:</b> ${escapeHtml(input.applicationName)}` : ""}${input.expiresAt ? `<br><b>Válido até:</b> ${date(input.expiresAt)}` : ""}</p><p>Acesse o painel para acompanhar sua aplicação.</p></div>`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export async function sendRenewalReminder(input: { userId: string; applicationName: string; expiresAt: Date; daysLeft: number }) { const user = await userEmail(input.userId); if (!user) return; const subject = `Seu plano vence em ${input.daysLeft} dia${input.daysLeft === 1 ? "" : "s"}`; const text = `Olá, ${user.name}.\n\nO plano da aplicação ${input.applicationName} vence em ${input.daysLeft} dia${input.daysLeft === 1 ? "" : "s"}, em ${date(input.expiresAt)}. Acesse o painel para renovar e evitar interrupção.`; const html = `<div style="font-family:Arial,sans-serif;max-width:560px;color:#1f2933"><h2>Renovação necessária</h2><p>O plano da aplicação <b>${escapeHtml(input.applicationName)}</b> vence em <b>${input.daysLeft} dia${input.daysLeft === 1 ? "" : "s"}</b>.</p><p>Vencimento: ${date(input.expiresAt)}</p><p>Acesse o painel para renovar antes da interrupção.</p></div>`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export async function sendReleaseUpdateAlert(input: { userId: string; productName: string; version: string; notes: string }) { const user = await userEmail(input.userId); if (!user) return; const subject = `Nova atualização disponível: ${input.productName} v${input.version}`; const text = `Olá, ${user.name}.\n\nUma nova atualização da aplicação ${input.productName} foi publicada.\nVersão: ${input.version}\n\n${input.notes || "Acesse o painel para ver os detalhes da atualização."}`; const html = `<div style="font-family:Arial,sans-serif;max-width:560px;color:#1f2933"><h2>Nova atualização disponível</h2><p>Uma nova versão da aplicação <b>${escapeHtml(input.productName)}</b> foi publicada.</p><p><b>Versão:</b> ${escapeHtml(input.version)}</p><div style="white-space:pre-wrap;border-left:3px solid #84cc16;padding-left:12px">${escapeHtml(input.notes || "Acesse o painel para ver os detalhes da atualização.")}</div><p>Acesse o painel para acompanhar a atualização.</p></div>`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export function loginContextFromHeaders(headers: Headers): LoginContext { const forwarded = headers.get("x-forwarded-for")?.split(",")[0]?.trim(); return { ip: forwarded || headers.get("x-real-ip") || "não informado", city: headers.get("x-vercel-ip-city") || "", region: headers.get("x-vercel-ip-country-region") || "", country: headers.get("x-vercel-ip-country") || "" }; }
