import nodemailer from "nodemailer";
import databases from "../databases";

type LoginContext = { ip: string; city: string; region: string; country: string };
export type CartNotification = { userId: string; cartId: string; type: "purchase" | "renewal"; productName: string; plan: string; amount: number; expiresAt?: Date | string | null; applicationName?: string };

function required(name: string): string { const value = process.env[name]?.trim(); if (!value) throw new Error(`A variável ${name} não está configurada.`); return value; }
function money(value: number): string { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value); }
function date(value?: Date | string | null): string { return value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)) : "—"; }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] || char); }
function transport() { const port = Number(process.env.EMAIL_SERVER_PORT || 587); return { host: required("EMAIL_SERVER_HOST"), port, secure: process.env.EMAIL_SERVER_SECURE === "true", auth: { user: required("EMAIL_SERVER_USER"), pass: required("EMAIL_SERVER_PASSWORD") }, connectionTimeout: 10_000, greetingTimeout: 10_000, socketTimeout: 15_000, requireTLS: process.env.EMAIL_SERVER_SECURE !== "true" }; }
function appUrl(path: string): string { const base = (process.env.NEXTAUTH_URL || process.env.NEXT_PUBLIC_APP_URL || "").replace(/\/$/, ""); return `${base}${path}` || path; }
function link(path: string): string { return escapeHtml(appUrl(path)); }
function row(label: string, value: string): string { return `<tr><td style="padding:9px 0;border-bottom:1px solid #1F2937;color:#94A3B8;font-size:13px;">${escapeHtml(label)}</td><td align="right" style="padding:9px 0;border-bottom:1px solid #1F2937;color:#F8FAFC;font-size:13px;font-weight:600;">${value}</td></tr>`; }
function details(rows: string): string { return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:22px 0 4px;">${rows}</table>`; }
function cta(label: string, path: string): string { return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:26px 0 8px;"><tr><td bgcolor="#D6FF63" style="border-radius:6px;"><a href="${link(path)}" style="display:inline-block;padding:13px 18px;color:#0B0F14;font-size:13px;font-weight:700;text-decoration:none;">${escapeHtml(label)}</a></td></tr></table>`; }
function emailLayout(input: { preheader: string; eyebrow: string; title: string; intro: string; body: string; action?: { label: string; path: string }; footerNote?: string }): string {
    return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>${escapeHtml(input.title)}</title></head><body style="margin:0;padding:0;background:#0B0F14;color:#F8FAFC;font-family:Arial,Helvetica,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(input.preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0B0F14;"><tr><td align="center" style="padding:28px 14px 44px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;"><tr><td style="padding:8px 4px 22px;"><span style="color:#D6FF63;font-size:15px;font-weight:800;letter-spacing:.22em;">ZUROS</span><span style="float:right;color:#94A3B8;font-size:11px;line-height:20px;">PLATAFORMA</span></td></tr><tr><td style="background:#111827;border:1px solid #1F2937;border-radius:8px;padding:34px 30px 30px;"><p style="margin:0 0 12px;color:#D6FF63;font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;">${escapeHtml(input.eyebrow)}</p><h1 style="margin:0;color:#F8FAFC;font-size:27px;line-height:1.2;letter-spacing:-.03em;">${escapeHtml(input.title)}</h1><p style="margin:16px 0 0;color:#94A3B8;font-size:15px;line-height:1.65;">${input.intro}</p>${input.body}${input.action ? cta(input.action.label, input.action.path) : ""}${input.footerNote ? `<p style="margin:24px 0 0;padding-top:18px;border-top:1px solid #1F2937;color:#94A3B8;font-size:12px;line-height:1.6;">${input.footerNote}</p>` : ""}</td></tr><tr><td style="padding:22px 4px 0;color:#64748B;font-size:11px;line-height:1.7;">Você recebeu este e-mail porque houve uma atividade na sua conta ZUROS.<br><a href="${link("/dashboard")}" style="color:#94A3B8;">Dashboard</a> · <a href="${link("/status")}" style="color:#94A3B8;">Status</a> · <a href="mailto:suporte@zuros.app" style="color:#94A3B8;">Suporte</a> · <a href="${link("/termos")}" style="color:#94A3B8;">Termos</a> · <a href="${link("/privacidade")}" style="color:#94A3B8;">Privacidade</a><br><span style="color:#475569;">© ZUROS — comunicação transacional automática.</span></td></tr></table></td></tr></table></body></html>`;
}

export async function sendTransactionalEmail(input: { to: string; subject: string; text: string; html: string }) { if (!input.to) return; const transporter = nodemailer.createTransport(transport()); await transporter.sendMail({ from: required("EMAIL_FROM"), replyTo: required("EMAIL_FROM"), to: input.to, subject: input.subject, text: input.text, html: input.html, headers: { "Auto-Submitted": "auto-generated", "X-Auto-Response-Suppress": "All" } }); }
async function userEmail(userId: string): Promise<{ email: string; name: string } | null> { const user = await databases.siteUsers.findOne({ discordId: userId }, { email: 1, name: 1 }).lean(); return user?.email ? { email: user.email, name: user.name || "cliente" } : null; }

export async function sendLoginAlert(input: { userId: string; method: "Discord" | "e-mail"; context: LoginContext }) { const user = await userEmail(input.userId); if (!user) return; const place = [input.context.city, input.context.region, input.context.country].filter(Boolean).join(", ") || "localização não informada"; const when = date(new Date()); const subject = "Novo acesso à sua conta ZUROS"; const text = `Olá, ${user.name}.\n\nDetectamos um novo acesso à sua conta ZUROS.\nMétodo: ${input.method}\nData: ${when}\nIP: ${input.context.ip}\nLocal aproximado: ${place}\n\nSe não foi você, entre em contato com o suporte.`; const html = emailLayout({ preheader: "Um novo acesso foi detectado na sua conta ZUROS.", eyebrow: "Segurança da conta", title: "Novo acesso detectado", intro: `Olá, ${escapeHtml(user.name)}. Detectamos um novo acesso à sua conta.`, body: details(row("Método", escapeHtml(input.method)) + row("Data", escapeHtml(when)) + row("IP", escapeHtml(input.context.ip)) + row("Local aproximado", escapeHtml(place))), action: { label: "Revisar acesso", path: "/dashboard/account" }, footerNote: "Se você não reconhece este acesso, altere sua senha do provedor e fale com o suporte." }); await sendTransactionalEmail({ to: user.email, subject, text, html }); }

export async function sendCartOpenedAlert(input: CartNotification) { const user = await userEmail(input.userId); if (!user) return; const kind = input.type === "renewal" ? "renovação" : "pedido"; const subject = `Seu ${kind} foi aberto na ZUROS`; const text = `Olá, ${user.name}.\n\nSeu ${kind} foi aberto.\nProduto: ${input.productName}\nPlano: ${input.plan}\nValor: ${money(input.amount)}\nValidade do carrinho: ${date(input.expiresAt)}\n\nAcesse o painel para concluir o pagamento.`; const html = emailLayout({ preheader: `Seu ${kind} está pronto para pagamento.`, eyebrow: kind === "renovação" ? "Renovação" : "Novo carrinho", title: kind === "renovação" ? "Sua renovação está pronta" : "Seu carrinho foi criado", intro: `Olá, ${escapeHtml(user.name)}. O ${kind} foi criado e está aguardando a próxima etapa.`, body: details(row("Produto", escapeHtml(input.productName)) + row("Plano", escapeHtml(input.plan)) + row("Valor", escapeHtml(money(input.amount))) + row("Expira em", escapeHtml(date(input.expiresAt)))), action: { label: "Abrir pagamento", path: `/dashboard/store/cart/${encodeURIComponent(input.cartId)}` }, footerNote: "O carrinho permanece sujeito ao prazo informado acima." }); await sendTransactionalEmail({ to: user.email, subject, text, html }); }

export async function sendPaymentConfirmedAlert(input: CartNotification) { const user = await userEmail(input.userId); if (!user) return; const kind = input.type === "renewal" ? "renovação" : "pedido"; const subject = `Pagamento aprovado: ${input.productName}`; const text = `Olá, ${user.name}.\n\nSeu pagamento foi aprovado.\nTipo: ${kind}\nProduto: ${input.productName}\nPlano: ${input.plan}\nValor: ${money(input.amount)}\n${input.applicationName ? `Aplicação: ${input.applicationName}\n` : ""}${input.expiresAt ? `Válido até: ${date(input.expiresAt)}\n` : ""}\nAcesse o painel para acompanhar sua aplicação.`; const html = emailLayout({ preheader: `Pagamento confirmado para ${input.productName}.`, eyebrow: "Pagamento confirmado", title: "Pagamento recebido", intro: `Olá, ${escapeHtml(user.name)}. O pagamento do seu ${kind} foi confirmado pelo sistema.`, body: details(row("Produto", escapeHtml(input.productName)) + row("Plano", escapeHtml(input.plan)) + row("Valor", escapeHtml(money(input.amount))) + (input.applicationName ? row("Aplicação", escapeHtml(input.applicationName)) : "") + (input.expiresAt ? row("Válido até", escapeHtml(date(input.expiresAt))) : "")), action: { label: "Abrir dashboard", path: "/dashboard" } }); await sendTransactionalEmail({ to: user.email, subject, text, html }); }

export async function sendRenewalReminder(input: { userId: string; applicationName: string; expiresAt: Date; daysLeft: number }) { const user = await userEmail(input.userId); if (!user) return; const days = `${input.daysLeft} dia${input.daysLeft === 1 ? "" : "s"}`; const subject = `Seu plano vence em ${days}`; const text = `Olá, ${user.name}.\n\nO plano da aplicação ${input.applicationName} vence em ${days}, em ${date(input.expiresAt)}. Acesse o painel para renovar e evitar interrupção.`; const html = emailLayout({ preheader: `O plano de ${input.applicationName} vence em ${days}.`, eyebrow: "Atenção necessária", title: "Sua renovação se aproxima", intro: `O plano da aplicação <strong style="color:#F8FAFC;">${escapeHtml(input.applicationName)}</strong> vence em <strong style="color:#D6FF63;">${escapeHtml(days)}</strong>.`, body: details(row("Aplicação", escapeHtml(input.applicationName)) + row("Vencimento", escapeHtml(date(input.expiresAt)))), action: { label: "Renovar aplicação", path: "/dashboard/invoices" }, footerNote: "Renove antes do vencimento para evitar interrupção do serviço." }); await sendTransactionalEmail({ to: user.email, subject, text, html }); }

function replaceTemplateTokens(template: string, values: Record<string, string>): string { return template.replace(/\{\{\s*([A-Z0-9_]+)\s*\}\}/g, (_, key: string) => values[key] || ""); }
function htmlToText(html: string): string { return html.replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<br\s*\/?>(?=.)/gi, "\n").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/\s{2,}/g, " ").trim(); }
export async function sendReleaseUpdateAlert(input: { userId: string; productName: string; version: string; notes: string }) { const user = await userEmail(input.userId); if (!user) return; const subject = `Nova atualização disponível: ${input.productName} v${input.version}`; const raw = input.notes.trim(); const custom = /<(!doctype\s+html|html\b|table\b|body\b|div\b)/i.test(raw); const customHtml = custom ? replaceTemplateTokens(raw, { CUSTOMER_NAME: escapeHtml(user.name), PRODUCT_NAME: escapeHtml(input.productName), VERSION: escapeHtml(input.version), DATE: escapeHtml(new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date())) }) : ""; const html = custom ? customHtml : emailLayout({ preheader: `Nova versão disponível para ${input.productName}.`, eyebrow: "Atualização disponível", title: "Sua aplicação pode ser atualizada", intro: `Uma nova versão de <strong style="color:#F8FAFC;">${escapeHtml(input.productName)}</strong> foi publicada.`, body: details(row("Versão", escapeHtml(input.version))) + `<p style="margin:22px 0 0;color:#94A3B8;font-size:14px;line-height:1.65;white-space:pre-wrap;border-left:2px solid #D6FF63;padding-left:14px;">${escapeHtml(raw || "Acesse o painel para ver os detalhes da atualização.")}</p>`, action: { label: "Ver atualização", path: "/dashboard" } }); const text = custom ? htmlToText(html) : `Olá, ${user.name}.\n\nUma nova atualização da aplicação ${input.productName} foi publicada.\nVersão: ${input.version}\n\n${raw || "Acesse o painel para ver os detalhes da atualização."}`; await sendTransactionalEmail({ to: user.email, subject, text, html }); }
export function loginContextFromHeaders(headers: Headers): LoginContext { const forwarded = headers.get("x-forwarded-for")?.split(",")[0]?.trim(); return { ip: forwarded || headers.get("x-real-ip") || "não informado", city: headers.get("x-vercel-ip-city") || "", region: headers.get("x-vercel-ip-country-region") || "", country: headers.get("x-vercel-ip-country") || "" }; }
