"use client";
import { useMemo, useState } from "react";
import { Card, TechnicalId, UserChip } from "./ui";
import { formatMoney } from "@/lib/status";
import type { CustomerEntry } from "@/lib/actions/vendas.actions";
export function CustomersTable({ customers }: { customers: CustomerEntry[] }) {
 const [query,setQuery]=useState(""); const [page,setPage]=useState(1); const size=20;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); return q?customers.filter(c=>`${c.userId} ${c.guildId||""}`.toLowerCase().includes(q)):customers},[customers,query]); const pages=Math.max(1,Math.ceil(filtered.length/size)); const visible=filtered.slice((page-1)*size,page*size);
 return <div className="space-y-3"><input className="h-10 w-full max-w-sm rounded-lg border border-white/10 bg-zinc-950 px-3 text-sm text-white outline-none focus:border-[var(--accent)]" placeholder="Buscar por usuário ou servidor" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b border-zinc-800 bg-zinc-950/60 text-xs uppercase tracking-wide text-zinc-500"><th className="p-4">Usuário</th><th className="p-4">Servidor</th><th className="p-4">Pedidos</th><th className="p-4">Total gasto</th><th className="p-4">Última compra</th></tr></thead><tbody>{visible.map(c=><tr key={c.userId} className="border-b border-zinc-900 text-zinc-300 transition last:border-0 hover:bg-zinc-900/40"><td className="p-4"><UserChip userId={c.userId}/></td><td className="p-4 text-zinc-400"><TechnicalId value={c.guildId} label="Servidor"/></td><td className="p-4">{c.orders}</td><td className="p-4 text-right font-semibold tabular-nums text-emerald-300">{formatMoney(c.totalSpent)}</td><td className="p-4 whitespace-nowrap">{c.lastPurchaseAt?new Date(c.lastPurchaseAt).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit"}):"—"}</td></tr>)}</tbody></table></div></Card>{filtered.length>size&&<div className="flex items-center justify-between text-xs text-zinc-500"><span>{filtered.length} resultado(s)</span><div className="flex gap-2"><button type="button" className="rounded border border-white/10 px-3 py-1.5 disabled:opacity-40" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button type="button" className="rounded border border-white/10 px-3 py-1.5 disabled:opacity-40" disabled={page>=pages} onClick={()=>setPage(page+1)}>Próxima</button></div></div>}</div>;
}
