"use client";
import { useMemo, useState } from "react";
import { Card, StatusBadge, TechnicalId, UserChip } from "./ui";
import { formatDate, formatMoney } from "@/lib/status";
import { STEP_LABELS } from "@/lib/vendas";
import type { OpenCartEntry } from "@/lib/actions/vendas.actions";
export function OpenCartsTable({ carts }: { carts: OpenCartEntry[] }) {
 const [query,setQuery]=useState(""); const [page,setPage]=useState(1); const size=20; const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?carts.filter(c=>`${c.userId} ${c.itemName} ${c.id} ${c.channelId||""} ${c.paymentId||""}`.toLowerCase().includes(q)):carts},[carts,query]); const pages=Math.max(1,Math.ceil(filtered.length/size)); const visible=filtered.slice((page-1)*size,page*size);
 return <div className="space-y-3"><input className="h-10 w-full max-w-sm rounded-lg border border-white/10 bg-zinc-950 px-3 text-sm text-white outline-none focus:border-[var(--accent)]" placeholder="Buscar por usuário, item ou referência" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead><tr className="border-b border-zinc-800 bg-zinc-950/60 text-xs uppercase tracking-wide text-zinc-500"><th className="p-4">Criado</th><th className="p-4">Tipo / item</th><th className="p-4">Usuário</th><th className="p-4">Etapa</th><th className="p-4">Plano</th><th className="p-4">Valor</th><th className="p-4">Expira</th><th className="p-4">Referências</th></tr></thead><tbody>{visible.map(c=><tr key={`${c.type}-${c.id}`} className="border-b border-zinc-900 text-zinc-300 transition last:border-0 hover:bg-zinc-900/40"><td className="p-4 whitespace-nowrap">{formatDate(c.createdAt)}</td><td className="p-4"><span className="block font-medium text-white">{c.itemName}</span><span className="text-xs text-zinc-500">{c.type==="renew"?"Renovação":"Compra"}</span></td><td className="p-4"><UserChip userId={c.userId}/></td><td className="p-4"><StatusBadge status={c.step} label={STEP_LABELS[c.step]}/></td><td className="p-4">{c.lifetime?"Vitalício":c.days?`${c.days} dias`:"Ainda não escolhido"}</td><td className="p-4 text-right font-semibold tabular-nums text-emerald-300">{formatMoney(c.finalPrice||c.price)}</td><td className="p-4 whitespace-nowrap">{c.expiresAt?formatDate(c.expiresAt):"—"}</td><td className="p-4 text-xs text-zinc-500"><span className="block"><TechnicalId value={c.channelId} label="Canal"/></span><span className="block"><TechnicalId value={c.paymentId} label="PIX"/></span><span className="block"><TechnicalId value={c.id} label="Carrinho"/></span></td></tr>)}</tbody></table></div></Card>{filtered.length>size&&<div className="flex items-center justify-between text-xs text-zinc-500"><span>{filtered.length} resultado(s)</span><div className="flex gap-2"><button type="button" className="rounded border border-white/10 px-3 py-1.5 disabled:opacity-40" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button type="button" className="rounded border border-white/10 px-3 py-1.5 disabled:opacity-40" disabled={page>=pages} onClick={()=>setPage(page+1)}>Próxima</button></div></div>}</div>;
}
