"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { beginAuthenticatorSetup, confirmAuthenticatorSetup, disableAuthenticator, getSecurityStatus } from "@/lib/actions/security.actions";
export function SecuritySettings() { const [enabled, setEnabled] = useState(false); const [setup, setSetup] = useState<{ secret: string; qrDataUrl: string } | null>(null); const [code, setCode] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); useEffect(() => { void getSecurityStatus().then((item) => setEnabled(item.totpEnabled)); }, []);
    async function start() { setLoading(true); setNotice(""); try { setSetup(await beginAuthenticatorSetup()); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível iniciar."); } finally { setLoading(false); } }
    async function confirm() { setLoading(true); setNotice(""); try { await confirmAuthenticatorSetup(code); setEnabled(true); setSetup(null); setCode(""); setNotice("Google Authenticator ativado nesta conta."); } catch (error) { setNotice(error instanceof Error ? error.message : "Código inválido."); } finally { setLoading(false); } }
    async function disable() { setLoading(true); try { await disableAuthenticator(code); setEnabled(false); setCode(""); setNotice("Autenticação adicional desativada."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível desativar."); } finally { setLoading(false); } }
    return <section className="security-settings"><header><p className="account-card-kicker">SEGURANÇA DA CONTA</p><h1>Proteja seu acesso</h1><p>Use um código temporário do Google Authenticator além do login por e-mail.</p></header><div className="security-status"><span className={enabled ? "is-on" : ""} /> <strong>{enabled ? "Autenticação em duas etapas ativada" : "Autenticação em duas etapas desativada"}</strong></div>{!enabled && !setup && <button type="button" onClick={() => void start()} disabled={loading} className="security-primary">Configurar Google Authenticator</button>}{setup && <div className="security-setup"><div><h2>Escaneie o QR Code</h2><p>Abra o Google Authenticator, toque em adicionar conta e escaneie este código.</p><img src={setup.qrDataUrl} alt="QR Code para configurar o Google Authenticator" /><code>{setup.secret}</code></div><div><label>Código de 6 dígitos<input inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} placeholder="000000" /></label><button type="button" onClick={() => void confirm()} disabled={loading}>Confirmar ativação</button></div></div>}{enabled && <div className="security-disable"><label>Para desativar, informe o código atual<input inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} /></label><button type="button" onClick={() => void disable()} disabled={loading}>Desativar autenticação adicional</button></div>}{notice && <p className="support-notice">{notice}</p>}</section>; }
