"use client";

import { useEffect, useState } from "react";
import { addSupportTicketMessage, createWebSupportTicket, listMySupportTickets } from "@/lib/actions/support.actions";

type Ticket = { id: string; subject: string; category: string; priority: string; status: string; createdAt: string; messages: Array<{ authorName: string; body: string; createdAt: string }> };
const statusLabel: Record<string, string> = { open: "Aberto", waiting_user: "Aguardando você", waiting_staff: "Com a equipe", closed: "Encerrado" };
const categoryLabel: Record<string, string> = { technical: "Problema técnico", application: "Aplicação", payment: "Pagamento", account: "Conta", store: "Loja", suggestion: "Sugestão" };

export function SupportPortal({ enabled, discordInviteUrl }: { enabled: boolean; discordInviteUrl: string }) {
    const [tickets, setTickets] = useState<Ticket[]>([]); const [selected, setSelected] = useState<Ticket | null>(null); const [message, setMessage] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
    const [form, setForm] = useState({ subject: "", category: "account", priority: "normal", body: "" });
    useEffect(() => { void listMySupportTickets().then((items) => setTickets(items as unknown as Ticket[])).catch(() => undefined); }, []);
    async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setNotice(""); try { const ticket = await createWebSupportTicket(form); setTickets((old) => [ticket as unknown as Ticket, ...old]); setSelected(ticket as unknown as Ticket); setForm({ subject: "", category: "account", priority: "normal", body: "" }); setNotice("Ticket aberto. A equipe responderá por este painel."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível abrir o ticket."); } finally { setLoading(false); } }
    async function sendMessage(event: React.FormEvent) { event.preventDefault(); if (!selected || !message.trim()) return; setLoading(true); try { const next = await addSupportTicketMessage(selected.id, message); setSelected(next as unknown as Ticket); setTickets((old) => old.map((item) => item.id === next.id ? next as unknown as Ticket : item)); setMessage(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível enviar a mensagem."); } finally { setLoading(false); } }
    return <div className="support-portal">
        <section className="support-hero"><div><p className="support-kicker">CENTRAL DE SUPORTE</p><h1>Ajuda quando você precisar.</h1><p>Abra um ticket pelo site ou fale diretamente com a comunidade no Discord.</p></div>{discordInviteUrl && <a className="support-discord-link" href={discordInviteUrl} target="_blank" rel="noreferrer">Entrar no Discord <span>↗</span></a>}</section>
        {!enabled && <div className="support-notice">O suporte via site está temporariamente indisponível.</div>}
        <div className="support-grid"><section className="support-panel"><header><p className="support-kicker">NOVO ATENDIMENTO</p><h2>Abra um ticket</h2><p>Descreva o problema com o máximo de detalhes possível.</p></header><form onSubmit={submit} className="support-form"><input required maxLength={160} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="Assunto do atendimento" /><div className="support-form-row"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{Object.entries(categoryLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Prioridade baixa</option><option value="normal">Prioridade normal</option><option value="high">Prioridade alta</option><option value="urgent">Urgente</option></select></div><textarea required maxLength={4000} rows={7} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} placeholder="Explique o que aconteceu..." /><button disabled={loading || !enabled}>{loading ? "Enviando..." : "Abrir ticket"}</button>{notice && <p className="support-notice">{notice}</p>}</form></section><section className="support-panel support-tickets"><header><p className="support-kicker">SEUS ATENDIMENTOS</p><h2>Tickets recentes</h2></header>{tickets.length === 0 ? <p className="support-empty">Você ainda não abriu tickets pelo site.</p> : <div className="support-ticket-list">{tickets.map((ticket) => <button type="button" key={ticket.id} onClick={() => setSelected(ticket)} className={selected?.id === ticket.id ? "is-selected" : ""}><span><strong>{ticket.subject}</strong><small>{categoryLabel[ticket.category] || ticket.category} · {new Date(ticket.createdAt).toLocaleDateString("pt-BR")}</small></span><em>{statusLabel[ticket.status] || ticket.status}</em></button>)}</div>}{selected && <div className="support-thread"><div className="support-thread-head"><strong>{selected.subject}</strong><button type="button" onClick={() => setSelected(null)}>Fechar</button></div>{selected.messages.map((item, index) => <article key={`${item.createdAt}-${index}`}><b>{item.authorName}</b><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString("pt-BR")}</small></article>)}{selected.status !== "closed" && <form onSubmit={sendMessage} className="support-reply"><textarea rows={3} value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Responder ao ticket..." /><button disabled={loading}>Enviar resposta</button></form>}</div>}</section></div>
    </div>;
}
